Code Quality: Update codes to pass php lint
WordPress/gutenberg-examples pull request #201
Opened 2022-03-24 04:47 UTC by t-hamano

I have noticed many errors in the php lint.
This PR updates codes to pass correctly based on what phpcs pointed out.

Mainly, I have addressed the following:

- Remove unnecessary spaces and line breaks
- Move `add_action` to after function to eliminate missing doc error.
- Space indent to tab indent
- Add missing `@package` tag
- Explicitly specify the fifth argument( `$in_footer` ) of `wp_register_script`
- Explicitly specify the 4th argument( `$ver` ) of `wp_register_style`
- add exclude pattern to phpcs.xml ( `node_modules`, `block.asset.php` )
- Use `require_once` instead of `include`

As this is my first PR, please do not hesitate to point out any problems.

2022-03-24 04:49 UTC, t-hamano commented on composer.json
> +		"lint": "phpcs --standard=phpcs.xml"
Probably a Windows-specific problem, the following error occurred:
```
'.' is not recognized as an internal or external command,
operable program or batch file.
Script ./vendor/bin/phpcs --standard=phpcs.xml handling the lint event returned with error code 1
```

I changed the way to specify the path according to [gutenberg repository](https://github.com/WordPress/gutenberg/blob/trunk/composer.json#L44).

2022-03-24 16:10 UTC, ryanwelcher requested changes
Thank you for taking the time to put this together!
Just a couple of notes/comments but overall looks great :)

2022-03-24 16:10 UTC, ryanwelcher commented on 09-code-data-basics-esnext/index.php
> +		get_bloginfo( 'version' ),
Can we reused the $asset_file['version'] here? My concern is that this will be cached until the version of WP changes.

2022-03-24 16:10 UTC, ryanwelcher commented on 10-dynamic-block/build/template.php
> +<p <?php echo wp_kses_data( get_block_wrapper_attributes() ); ?>>
nice 👍

2022-03-24 16:10 UTC, ryanwelcher commented on composer.json
> +		"lint": "phpcs --standard=phpcs.xml"
This command doesn't work for me anymore:
``` 
[InvalidArgumentException]                     
Script "phpcs" is not defined in this package
```
Let's revert this for now and come back to it in a secondary PR where we can come up with a good cross-platform approach.

2022-03-24 16:10 UTC, ryanwelcher commented on plugin-sidebar/plugin-sidebar.php
> +		get_bloginfo( 'version' ),
Same concern about the asset version being tied to the WP version.

2022-03-25 01:24 UTC, t-hamano commented
Thank you for reviewing the code !
I have pushed the update.

2022-03-30 15:20 UTC, ryanwelcher approved these changes
LGTM 👍  - thanks again for putting this together!

2022-03-30 17:35 UTC, merged