Add Site Title to Dynamic Block
WordPress/gutenberg-examples pull request #216
Opened 2022-04-29 20:46 UTC by salcode

I appreciate @ryanwelcher's [suggestion on simplifying](https://github.com/WordPress/gutenberg-examples/pull/205#discussion_r838822054) PR #205

This PR adds the `Site Title` option value (found at `Settings` > `General`)

![image](https://user-images.githubusercontent.com/5194588/166066706-2741a795-0345-41e8-ae67-4cc558231ac0.png)

and adds it to the "10-dynamic-block" example.

## Front End

![image](https://user-images.githubusercontent.com/5194588/166066819-a097c352-59f2-4d8f-8785-4364227b9b2d.png)

## In the Editor

![image](https://user-images.githubusercontent.com/5194588/166066849-5f1be1c4-bd26-4ebd-92c3-c5ac55a43c08.png)

Note: In the editor the Site Title (in this case "gutenberg-examples") can not be modified.

Resolves #203

2022-05-11 18:51 UTC, ryanwelcher requested changes
Just one small comment but overall this looks great to me!

We've made some pretty big structural changes to the repo so there are a lot of merge conflicts to resolve as well.

2022-05-11 18:51 UTC, ryanwelcher commented on 10-dynamic-block/src/edit.js
> +		( select ) => select( 'core' ).getSite() ?? {},
I believe that `title` is going to always be undefined until the store resolves because you're destructuring it out of an empty object. Perhaps we can add a default value or show a loading state if the `title` is undefined?

2022-05-27 19:36 UTC, salcode commented on 10-dynamic-block/src/edit.js
> +		( select ) => select( 'core' ).getSite() ?? {},
Great point. I've added a simple `loading...` message while the value is loading in 011003e

I'm trying to balance creating a good experience while keeping things simple but I'm open to feedback.

2022-05-27 19:43 UTC, ryanwelcher commented on 10-dynamic-block/src/edit.js
> +		( select ) => select( 'core' ).getSite() ?? {},
LGMT!

2022-05-27 19:44 UTC, ryanwelcher commented
Just looks like there are some linting issues to address but after that I think we can merge this!

2022-05-27 21:04 UTC, salcode commented
I'm seeing linting issues, which I will revisit and update this PR.

2022-05-27 22:28 UTC, salcode commented
Linting issues should be resolved now.

2022-05-28 01:53 UTC, ryanwelcher approved these changes
Thanks for putting this together. It's a nice addition!

2022-06-24 14:03 UTC, salcode commented
Is there anything else I can do to help get this merged now that the PR is approved?

2022-06-24 14:07 UTC, merged

2022-06-24 14:08 UTC, ryanwelcher commented
@salcode thanks for the follow-up! I was assuming that you could merge. At any rate, it's merged, and once again thanks for your contribution 😄

2022-06-24 19:58 UTC, salcode commented
Ha ha, I appreciate your overestimating my powers 😀 @ryanwelcher 

Thanks for the merge! Have a great weekend.